config/routes.rb
DchapmanIo::Application.routes.draw do
  root 'posts#index'

  devise_for :users, :path => "auth",
    :path_names   => {
    :sign_in      => 'login',
    :sign_out     => 'logout',
    :password     => 'secret',
    :confirmation => 'verification',
    :unlock       => 'unblock',
  }

  resources :posts

  get :blog, controller: 'posts', action: 'index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend ::FriendlyId
  friendly_id :title, use: :slugged

  default_scope order('created_at DESC')

  validates :title, uniqueness: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_start_time
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_start_time
    @start_time = Time.now.usec
  end

  def authentication_required
    redirect_to root_path, notice: "Authentication required." unless current_user.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authentication_required, only: [:edit, :update, :create, :new, :destroy]

  # GET /posts
  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.atom
    end
  end

  # GET /posts/1
  def show
    @post = Post.where(slug: params[:id]).first
    @page_title = @post.title
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.where(slug: params[:id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_load_time
    auth_link = link_to %(&epsilon;).html_safe, new_user_session_path
    "Page Rendered in #{sprintf('%.3f', (Time.now.usec - @start_time).abs / 1000000.0)}&plusmn;#{auth_link} seconds."
  end

  def current_url
    url_for(:only_path => false)
  end
  
  def page_title
    @page_title.present? ? "#{@page_title} | dchapman.io" :  "David Chapman | dchapman.io"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_markdown(md_text_string)
    BlueCloth.new(md_text_string).to_html
  end

  def time_of_post(time_obj)
    date = time_obj.strftime("%m/%d/%Y")
    time = time_obj.strftime("%k:%M")
    distance = distance_of_time_in_words_to_now(time_obj)
    "#{date} @ #{time} (#{distance} ago)"
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title= page_title
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Droid+Sans", media: "all"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield(:javascripts)
    = yield(:meta)
    = render partial: 'shared/meta'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  body
    header
      span.social_buttons
        = link_to('https://twitter.com/end_guy', class: 'twitter', target: '_blank')
          i class="fi-social-twitter"
        = link_to('https://facebook.com/dchapman1988', class: 'fi-social-facebook', target: '_blank')
          i class="social foundicon-facebook"
        = link_to('https://plus.google.com/117438777615476396633/', class: 'google-plus', target: '_blank')
          i class="fi-social-google-plus"
        = link_to('https://github.com/dchapman1988', class: 'github', target: '_blank')
          i class="fi-social-github"
        = link_to('/blog.atom', class: 'rss', target: '_blank')
          i class="fi-rss"
      h1.header
        = link_to(image_tag('ruby_icon.png', class: 'logo') + 'david@dchapman.io', root_path)
    - if notice.present?
      notice
        = notice
        =link_to('#', id: 'close_notice')
          span#close_notice_button
            | &#10006;
    = yield
    footer
      pre
        span.page_load_time= page_load_time.html_safe
        span.copy_right
          = "Copyright © #{Time.now.year} - David A. Chapman"
    = javascript_include_tag "disqus_comment_counter"

app/views/posts/_disqus_thread.html.slim
#disqus_thread
javascript:
  var disqus_shortname  = 'dchapman-io';
  var disqus_identifier = "#{@post.slug}";
  var disqus_title      = "#{@post.title} | dchapman.io";
  var disqus_url        = "#{current_url.to_s}";
  (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
noscript
  You must enable JavaScript to view the comments here.

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit 'Save'

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
= link_to 'New Post', new_post_path if current_user.present?

div.blog_wrapper
  - @posts.each do |post|
    div.post
      span.date_of_post= time_of_post(post.created_at)
      h2.post_title
        = link_to post.title, post
      div.post_body
        = render_markdown(post.body).html_safe
      div.post_actions
        = link_to %(comments).html_safe, %(#{post_path(post)}#disqus_thread), anchor: "disqus_thread", :"data-disqus-identifer" => post.slug
        = link_to %(read more&rarr;).html_safe, post, class: 'go_back_link'
        - if current_user.present?
          = link_to 'Show', post
          = link_to 'Edit', edit_post_path(post)
          = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
div.post
  span.date_of_post= time_of_post(@post.created_at)
  h2.post_title
    = link_to @post.title, @post
  div.post_body
    = render_markdown(@post.body).html_safe
  div.actions
    = link_to "&larr;go back".html_safe, root_path, class: 'go_back_link'
    - if current_user.present?
      = link_to 'Show', @post
      = link_to 'Edit', edit_post_path(@post)
      = link_to 'Destroy', @post, :confirm => 'Are you sure?', :method => :delete
  div.comments
    = render partial: "disqus_thread"

app/views/shared/_disqus_comment_counter.html.slim
javascript:
  var disqus_shortname = 'dchapman-io'; // required: replace example with your forum shortname
  (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());

app/views/shared/_meta.html.erb
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width" />
<meta name="description" content="The personal website of software engineer, David A. Chapman." />
<meta name="keywords" content="HTML,Ruby,Rails,Programming,Engineering,Computer,Science,Software,Development" />
<meta name="author" content="David A. Chapman" />
<meta property="og:url" content="<%= url_for(:only_path => false) %>" />
<meta property="og:type" content="website" />
<meta property="og:title" content="<%= @page_title %>" />
<meta property="og:description" content="The personal website of software engineer, David A. Chapman." />
<meta property="og:image" content="" />

app/views/shared/_social_icons.html.erb
<a href="../icon/github-sign"><i class="icon-github-sign"></i></a>